In [1]:
import numpy as np

# DataType

In [2]:
# ndarray
a1=np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [3]:
a2=np.array([[1,2,3],[4,5,6]])

In [4]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3=np.array([[[[1,2,3],[4,5,6]]]])

In [6]:
a3

array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [7]:
a3.size

6

In [8]:
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# creating NP Array

In [9]:
sample_array=np.array([1,2,3])

In [10]:
sample_array.dtype

dtype('int32')

In [11]:
type(sample_array)

numpy.ndarray

In [12]:
one=np.ones((2,3))


In [13]:
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
one.dtype

dtype('float64')

In [18]:
type(one
    )

numpy.ndarray

In [19]:
zero=np.zeros((2,3))

In [20]:
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array=np.arange(0,9,2)
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array=np.random.randint(1,30,size=(8,1))

In [37]:
random_array

array([[12],
       [ 1],
       [ 4],
       [ 3],
       [10],
       [10],
       [28],
       [10]])

In [39]:
np.random.random((2,3))

array([[0.14191113, 0.05763889, 0.62285793],
       [0.08828768, 0.52741659, 0.52472755]])

In [45]:
type(random_array.shape)

tuple

In [55]:
np.random.rand(5,3)

array([[0.80450762, 0.69032368, 0.12699417],
       [0.00871334, 0.60866792, 0.35703476],
       [0.55307368, 0.51951984, 0.668649  ],
       [0.39660368, 0.89867166, 0.30665912],
       [0.87429189, 0.00413972, 0.648923  ]])

In [78]:
# pseudo random numbers
np.random.seed(seed=0)

In [79]:
random_array_4=np.random.randint(10,size=(4,7))

In [80]:
random_array_4

array([[5, 0, 3, 3, 7, 9, 3],
       [5, 2, 4, 7, 6, 8, 8],
       [1, 6, 7, 7, 8, 1, 5],
       [9, 8, 9, 4, 3, 0, 3]])

# Viewing 

In [81]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
random_array=np.random.randint(10,size=(3,5))

In [3]:
random_array


array([[8, 6, 3, 3, 1],
       [1, 7, 4, 1, 7],
       [9, 4, 0, 4, 5]])

In [4]:
np.sort(random_array)

array([[1, 3, 3, 6, 8],
       [1, 1, 4, 7, 7],
       [0, 4, 4, 5, 9]])

In [5]:
np.argsort(random_array)

array([[4, 2, 3, 1, 0],
       [0, 3, 2, 1, 4],
       [2, 1, 3, 4, 0]], dtype=int64)

In [7]:
from matplotlib.image import imread as img
panda=img('panda.png')

In [10]:
panda.size

24465000

In [11]:
panda.shape

(2330, 3500, 3)